name: 'Run Docket Tests'
description: 'Makes a request to the Docket API, waits for and reports test results'
author: 'Docket Technologies Inc.'

inputs:
  apiKey:
    description: 'Docket API key for authentication'
    required: true
    sensitive: true

  testParameters:
    description: 'JSON string containing parameters to send to the Docket API. Must be valid JSON format.'
    required: true
    default: '{}'
  repositoryFullName:
    description: 'Name of the repository'
    required: true

outputs:
  runId:
    description: 'The run ID of the Docket API request'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'send'
  color: 'blue'
